### PR TITLE
Fix discord_components not in the correct version.

### PR DESCRIPTION
**Pull request by Huguitis**

### CODE REVIEW

**Comment by Not-Bay** [comment]
Is there any particular reason of why you think this is a needed change?

**Comment by Huguitis** [comment]
Since discord_components in the necessary version is not available by installing it with pip and that version also not in the official repository, I was able to get the necesarry version and upload it to my discord_components froked repository. Lobbybot only works on that version, you can check it.

**Comment by Not-Bay** [comment]
Thank you, just for security can you change the fork repo to `https://github.com/BayGamerYT/discord.py-components`

**Comment by Huguitis** [comment]
Alright, all is done.

**Pull request merged**
